import '../../models/exam_paper_model.dart';

const class11English2025Annual = ExamPaperData(
  paperId: 'class11-english-2025-annual',
  title: '2025 Annual Exam Paper',
  classLabel: 'Class 11',
  subject: 'English',
  duration: '3 Hours',
  maximumMarks: 90,
  totalPages: 8,
  pages: [
    ExamPage(
      pageNumber: 1,
      blocks: [
        ExamBlock(type: 'paper_header', content: 'Language — Part II — English'),
        ExamBlock(
          type: 'metadata_row',
          items: [
            MetadataItem(label: 'Time', value: '3 Hours'),
            MetadataItem(label: 'Maximum Marks', value: '90'),
            MetadataItem(label: 'Total Pages', value: '8'),
          ],
        ),
        ExamBlock(
          type: 'instructions',
          content: '(1) Check the question paper for fairness of printing. If there is any lack of fairness, inform the Hall Supervisor immediately.\n(2) Use Blue or Black ink to write and underline and pencil to draw diagrams.',
        ),
        ExamBlock(type: 'part_heading', content: 'PART - I'),
        ExamBlock(type: 'instructions', content: 'Answer all the questions. 20x1=20'),
        ExamBlock(type: 'instructions', content: 'Choose the appropriate synonyms of the underlined words in the following sentences.'),
        ExamBlock(
          type: 'mcq_question',
          questionId: 'q1',
          marks: 1,
          content: 'The common link of friendship was snapped.',
          options: ['attached', 'cut', 'clicked', 'joined'],
        ),
        ExamBlock(
          type: 'mcq_question',
          questionId: 'q2',
          marks: 1,
          content: 'With this princely sum, I left for the US.',
          options: ['very large', 'royal', 'heavy', 'meagre'],
        ),
        ExamBlock(
          type: 'mcq_question',
          questionId: 'q3',
          marks: 1,
          content: 'There was no sound but a curious smothered noise from my friend.',
          options: ['unwanted', 'thickened', 'unexpected', 'suppressed'],
        ),
        ExamBlock(type: 'instructions', content: 'Choose the appropriate antonyms for the underlined words in the following sentences.'),
        ExamBlock(
          type: 'mcq_question',
          questionId: 'q4',
          marks: 1,
          content: 'I am always reluctant to trust a departing visitor.',
          options: ['disinterested', 'keen', 'rebellious', 'unwilling'],
        ),
        ExamBlock(
          type: 'mcq_question',
          questionId: 'q5',
          marks: 1,
          content: 'Robust optimism will be discouraged.',
          options: ['encouraged', 'compelled', 'pressurised', 'suppressed'],
        ),
        ExamBlock(
          type: 'mcq_question',
          questionId: 'q6',
          marks: 1,
          content: 'I never did my frequent flyer miles, by the way.',
          options: ['often', 'rare', 'customary', 'always'],
        ),
      ],
    ),
    ExamPage(
      pageNumber: 2,
      blocks: [
        ExamBlock(
          type: 'mcq_question',
          questionId: 'q7',
          marks: 1,
          content: 'Choose the expanded form of GST.',
          options: ['Gross Sales Tax', 'Goods and Sales Tax', 'Goods and Service Tax', 'Grocery Service Tax'],
        ),
        ExamBlock(
          type: 'mcq_question',
          questionId: 'q8',
          marks: 1,
          content: 'Choose the word that can be placed after the word water to form a compound word.',
          options: ['lead', 'sea', 'wet', 'proof'],
        ),
        ExamBlock(
          type: 'mcq_question',
          questionId: 'q9',
          marks: 1,
          content: 'Form a derivative by adding a suitable suffix to the root word peace.',
          options: ['-ness', '-ful', '-ly', '-able'],
        ),
        ExamBlock(
          type: 'mcq_question',
          questionId: 'q10',
          marks: 1,
          content: 'Add a suitable prefix to form the opposite of the word breakable.',
          options: ['mis', 'in', 'en', 'un'],
        ),
        ExamBlock(
          type: 'mcq_question',
          questionId: 'q11',
          marks: 1,
          content: 'Choose the appropriate article for the following sentence.\nI gave __________ one rupee coin to my brother.',
          options: ['a', 'an', 'some', 'the'],
        ),
        ExamBlock(
          type: 'mcq_question',
          questionId: 'q12',
          marks: 1,
          content: 'Choose the correct modal verb for the following sentence.\nWhen Koushik was a child, he __________ play in the street.',
          options: ['must', 'would', 'may', 'will'],
        ),
        ExamBlock(
          type: 'mcq_question',
          questionId: 'q13',
          marks: 1,
          content: 'The dog jumped __________ the river.',
          options: ['into', 'above', 'in', 'under'],
        ),
        ExamBlock(
          type: 'mcq_question',
          questionId: 'q14',
          marks: 1,
          content: 'Choose the correct clipped form for the word perambulator.',
          options: ['bulator', 'peram', 'pramb', 'pram'],
        ),
      ],
    ),
    ExamPage(
      pageNumber: 3,
      blocks: [
        ExamBlock(
          type: 'mcq_question',
          questionId: 'q15',
          marks: 1,
          content: 'Choose the correct meaning of the idiom "alarm bells ringing".',
          options: ['try any method', 'sign of something going wrong', 'abandoning in difficulty', 'in serious difficulty'],
        ),
        ExamBlock(
          type: 'mcq_question',
          questionId: 'q16',
          marks: 1,
          content: 'A person who treats the problems of the heart is a __________.',
          options: ['pulmonologist', 'neurologist', 'cardiologist', 'nephrologist'],
        ),
        ExamBlock(
          type: 'mcq_question',
          questionId: 'q17',
          marks: 1,
          content: "Madhav doesn't speak Telugu, __________",
          options: ['has he ?', 'did he ?', 'is he ?', 'does he ?'],
        ),
        ExamBlock(
          type: 'mcq_question',
          questionId: 'q18',
          marks: 1,
          content: 'Choose the meaning of the foreign word - in toto.',
          options: ['completely', 'half', 'partially', 'null'],
        ),
        ExamBlock(
          type: 'mcq_question',
          questionId: 'q19',
          marks: 1,
          content: 'Choose the word that has been wrongly spelt.',
          options: ['revolution', 'reverance', 'reference', 'relevant'],
        ),
        ExamBlock(
          type: 'mcq_question',
          questionId: 'q20',
          marks: 1,
          content: 'Fill in the blank with the correct determiner.\nAnand invited ___________ friends for his birthday party.',
          options: ['few', 'a little', 'a few', 'little'],
        ),
        ExamBlock(type: 'part_heading', content: 'PART - II'),
        ExamBlock(type: 'section_heading', content: 'SECTION - 1'),
        ExamBlock(type: 'instructions', content: 'Answer any four of the following. 4x2=8'),
        ExamBlock(
          type: 'multi_subquestion',
          questionId: 'q21',
          marks: 2,
          content: 'Cocktail face, with all their conforming smiles like a fixed portrait smile.',
          subQuestions: [
            ExamSubQuestion(id: 'q21a', label: 'a', content: "What is meant by 'cocktail face' ?", marks: 1),
            ExamSubQuestion(id: 'q21b', label: 'b', content: 'Mention the figure of speech.', marks: 1),
          ],
        ),
      ],
    ),
    ExamPage(
      pageNumber: 4,
      blocks: [
        ExamBlock(
          type: 'multi_subquestion',
          questionId: 'q22',
          marks: 2,
          content: 'When snaps the knee, and cracks the wrist, when officialdom demands,',
          subQuestions: [
            ExamSubQuestion(id: 'q22a', label: 'a', content: 'Identify the literary device in these lines.', marks: 1),
            ExamSubQuestion(id: 'q22b', label: 'b', content: 'Whom does the officialdom demand ?', marks: 1),
          ],
        ),
        ExamBlock(
          type: 'multi_subquestion',
          questionId: 'q23',
          marks: 2,
          content: 'I heard a thousand blended notes\nWhile in a grove I sate reclined,',
          subQuestions: [
            ExamSubQuestion(id: 'q23a', label: 'a', content: 'What did the poet hear ?', marks: 1),
            ExamSubQuestion(id: 'q23b', label: 'b', content: 'Where did he sit ?', marks: 1),
          ],
        ),
        ExamBlock(
          type: 'multi_subquestion',
          questionId: 'q24',
          marks: 2,
          content: 'His coat is dusty from neglect, his whiskers are uncombed.\nHe sways his head from side to side, with movements like a snake;',
          subQuestions: [
            ExamSubQuestion(id: 'q24a', label: 'a', content: 'How does the cat look ?', marks: 1),
            ExamSubQuestion(id: 'q24b', label: 'b', content: 'What is the figure of speech used in the second line ?', marks: 1),
          ],
        ),
        ExamBlock(
          type: 'multi_subquestion',
          questionId: 'q25',
          marks: 2,
          content: "Defeat we repel, courage our fort;\nCringing from others we haven't done,",
          subQuestions: [
            ExamSubQuestion(id: 'q25a', label: 'a', content: 'What do they repel ?', marks: 1),
            ExamSubQuestion(id: 'q25b', label: 'b', content: 'What is their fort ?', marks: 1),
          ],
        ),
        ExamBlock(
          type: 'multi_subquestion',
          questionId: 'q26',
          marks: 2,
          content: 'And that small model of the barren earth\nWhich serves as paste and cover to our bones.',
          subQuestions: [
            ExamSubQuestion(id: 'q26a', label: 'a', content: 'What does "small model" mean ?', marks: 1),
            ExamSubQuestion(id: 'q26b', label: 'b', content: 'Who speaks these words ?', marks: 1),
          ],
        ),
        ExamBlock(type: 'section_heading', content: 'SECTION - 2'),
        ExamBlock(type: 'instructions', content: 'Answer any three of the following questions. 3x2=6'),
        ExamBlock(
          type: 'question',
          questionId: 'q27',
          marks: 2,
          content: 'Sharmila said, "I haven\'t seen her".\n[Change into indirect speech]',
        ),
        ExamBlock(
          type: 'question',
          questionId: 'q28',
          marks: 2,
          content: 'The teacher distributed the text books.\n[Change the voice]',
        ),
        ExamBlock(
          type: 'question',
          questionId: 'q29',
          marks: 2,
          content: 'In spite of her weakness, Radha attended the class.\n[Rewrite as a compound sentence]',
        ),
        ExamBlock(
          type: 'question',
          questionId: 'q30',
          marks: 2,
          content: 'You did not run fast. You did not catch the train.\n[Combine using "If"]',
        ),
      ],
    ),
    ExamPage(
      pageNumber: 5,
      blocks: [
        ExamBlock(type: 'part_heading', content: 'PART - III'),
        ExamBlock(type: 'section_heading', content: 'SECTION - 1'),
        ExamBlock(type: 'instructions', content: 'Explain any two of the following with reference to the context. 2x3=6'),
        ExamBlock(
          type: 'question',
          questionId: 'q31',
          marks: 3,
          content: 'With all my heart I do admire\nAthletes who sweat for fun or hire,',
        ),
        ExamBlock(
          type: 'question',
          questionId: 'q32',
          marks: 3,
          content: 'The birds around me hopped and played\nTheir thoughts I cannot measure,',
        ),
        ExamBlock(
          type: 'question',
          questionId: 'q33',
          marks: 3,
          content: 'Ours is a path of dignity and honour,',
        ),
        ExamBlock(type: 'section_heading', content: 'SECTION - 2'),
        ExamBlock(type: 'instructions', content: 'Answer any two of the following questions in not more than 30 words. 2x3=6'),
        ExamBlock(
          type: 'question',
          questionId: 'q34',
          marks: 3,
          content: 'What made the dogs to follow the grandmother after school hours ?',
        ),
        ExamBlock(
          type: 'question',
          questionId: 'q35',
          marks: 3,
          content: 'How do the chemists make fortunes out of the medicines people forget to take ?',
        ),
        ExamBlock(
          type: 'question',
          questionId: 'q36',
          marks: 3,
          content: 'Describe the fluttery cascade of things tumbling from the bag.',
        ),
        ExamBlock(type: 'section_heading', content: 'SECTION - 3'),
        ExamBlock(type: 'instructions', content: 'Answer any three of the following. 3x3=9'),
        ExamBlock(
          type: 'question',
          questionId: 'q37',
          marks: 3,
          content: 'Read the information in the table below and write three sentences on your inference about the data given.',
        ),
        ExamBlock(
          type: 'table',
          headers: ['S.No.', 'Event', 'Year', 'Affected Area'],
          rows: [
            ['1', 'Earthquake', '2001', 'Bhuj, Gujarat'],
            ['2', 'Tsunami', '2004', 'Tamilnadu Coastal line, Kerala, Andaman and Nicobar and Puducherry'],
            ['3', 'Cyclone', '2008', 'Tamilnadu'],
            ['4', 'Floods', '2015', 'Tamilnadu'],
          ],
        ),
      ],
    ),
    ExamPage(
      pageNumber: 6,
      blocks: [
        ExamBlock(
          type: 'question',
          questionId: 'q38',
          marks: 3,
          content: "Study the pie-chart carefully and answer the questions that follow.\nThe above pie-chart shows the monthly spending percentage of Arjun's family.",
        ),
        ExamBlock(
          type: 'chart_image',
          src: '',
          altText: "Pie chart showing monthly spending percentage of Arjun's family across categories including Education, Savings, Rent, Food, Entertainment, and Clothes.",
          caption: '',
          renderHint: 'image',
        ),
        ExamBlock(
          type: 'multi_subquestion',
          questionId: 'q38sub',
          marks: 3,
          content: 'Answer the following based on the pie-chart.',
          subQuestions: [
            ExamSubQuestion(
              id: 'q38suba',
              label: 'i',
              content: 'Arjun spends equally on __________.\n(a) Education and Savings (b) Rent and Food (c) Entertainment and Rent (d) Food and Education',
              marks: 1,
            ),
            ExamSubQuestion(
              id: 'q38subb',
              label: 'ii',
              content: 'He spends least on __________.\n(a) Education (b) Savings (c) Clothes (d) Entertainment',
              marks: 1,
            ),
            ExamSubQuestion(
              id: 'q38subc',
              label: 'iii',
              content: "Arjun's income is Rs. 16,000. Calculate the amount spent by him on Education.\n(a) 2000 (b) 3200 (c) 2400 (d) 1500",
              marks: 1,
            ),
          ],
        ),
        ExamBlock(
          type: 'question',
          questionId: 'q39',
          marks: 3,
          content: 'Describe the process of making a cup of coffee.',
        ),
        ExamBlock(
          type: 'multi_subquestion',
          questionId: 'q40',
          marks: 3,
          content: 'Expand the following News Headlines.',
          subQuestions: [
            ExamSubQuestion(id: 'q40a', label: 'i', content: 'Inflow into Mettur Dam reduces.', marks: 1),
            ExamSubQuestion(id: 'q40b', label: 'ii', content: 'Big cash prizes for Indian Olympic participants.', marks: 1),
            ExamSubQuestion(id: 'q40c', label: 'iii', content: 'Chennai collector to inaugurate Naan Mudhalvan Scheme.', marks: 1),
          ],
        ),
        ExamBlock(type: 'part_heading', content: 'PART - IV'),
        ExamBlock(type: 'instructions', content: 'Answer the following in a paragraph of about 150 words. 7x5=35'),
        ExamBlock(
          type: 'or_question',
          questionId: 'q41',
          marks: 5,
          optionA: ExamBlockOption(content: 'The Grandmother was strong-minded. Justify'),
          optionB: ExamBlockOption(content: 'How do universities mould students apart from imparting academic education to them ?'),
        ),
        ExamBlock(
          type: 'question',
          questionId: 'q42intro',
          marks: 0,
          content: 'Answer the following in a paragraph of about 150 words.',
        ),
        ExamBlock(
          type: 'or_question',
          questionId: 'q42',
          marks: 5,
          optionA: ExamBlockOption(content: 'The poet Ogden Nash does not wish to exchange places with the athletes. Justify his views.'),
          optionB: ExamBlockOption(content: 'Describe the appearance and qualities of Macavity.'),
        ),
        ExamBlock(
          type: 'question',
          questionId: 'q43intro',
          marks: 0,
          content: 'Answer in a paragraph of about 150 words by developing the following hints.',
        ),
        ExamBlock(
          type: 'or_question',
          questionId: 'q43',
          marks: 5,
          optionA: ExamBlockOption(content: 'Patients waiting - dentist clinic - everybody tensed - one woman - photos - dentist arrives - Joe enters - nurse - hammer - pliers - hacksaw - everyone frightened - boy confesses - girl weeps - everyone leaves - Joe returns - woman - the first patient'),
          optionB: ExamBlockOption(content: 'Aunt Jane - visited Jack and Jill - shocked seeing - radiogram - piano - car - furniture - enquired - source of income - Jack replied EMI - she told her motto of life - left the house - little cheque of ten pounds - Jill - baby - owned'),
        ),
      ],
    ),
    ExamPage(
      pageNumber: 7,
      blocks: [
        ExamBlock(
          type: 'question',
          questionId: 'q44intro',
          marks: 0,
          content: 'Summarize or make notes of the following passage.',
        ),
        ExamBlock(
          type: 'or_question',
          questionId: 'q44',
          marks: 5,
          optionA: ExamBlockOption(
            content: "Kabbadi is a contact team sport that originated in Tamil Nadu, India. It is the national sport of Bangladesh. It is also popular in South Asia and is the state game of the Indian states of Tamil Nadu, Kerala, Andhra Pradesh, Bihar, Haryana, Karnataka, Maharashtra, Punjab and Telangana. Kabbadi is played between two teams of seven players : the objective of the game is for a single player on offence referred to as a 'raider', to run into the opposing teams half of a court, tag out as many of their defenders as possible, and return to their own half of the court - all without being tackled by the defenders. Points are scored for each player tagged by the raider, while the opposing team earns a point for stopping the raider. Players are taken out of the game if they are tagged or tackled, but can be 'revived' for each point scored by their team from a tag or tackle. The raider should hold his breath and utter the words like 'Kabbadi Kabbadi, hututu hututu, chadu kudu' etc. while the opponents try to catch him. If he stops uttering these words, he is considered out. The highest governing body of kabbadi is the International Kabbadi Federation.",
          ),
          optionB: ExamBlockOption(content: "Write a paragraph on 'Truth alone Triumphs' in about 150 words."),
        ),
        ExamBlock(
          type: 'question',
          questionId: 'q45intro',
          marks: 0,
          content: 'Respond to the given advertisement and prepare a bio-data considering yourself fulfilling the conditions specified.\n[Write XXXX for your name and YYYY for the address]',
        ),
        ExamBlock(
          type: 'paragraph_text',
          content: 'Wanted\nACCOUNTANT\nThe applicant should be a graduate with fluency in English and five years experience.\nApply to\nThe Manager,\nAlpha Enterprises,\nNo.15, State Bank colony,\nChennai - 600091.',
        ),
        ExamBlock(
          type: 'or_question',
          questionId: 'q45',
          marks: 5,
          optionA: ExamBlockOption(content: 'Respond to the given advertisement and prepare a bio-data considering yourself fulfilling the conditions specified.\n[Write XXXX for your name and YYYY for the address]'),
          optionB: ExamBlockOption(content: 'Write a letter to your friend about your trip to Kodaikanal.'),
        ),
      ],
    ),
    ExamPage(
      pageNumber: 8,
      blocks: [
        ExamBlock(
          type: 'question',
          questionId: 'q46intro',
          marks: 0,
          content: 'Read the following sentences, spot the errors and rewrite the sentences correctly.',
        ),
        ExamBlock(
          type: 'or_question',
          questionId: 'q46',
          marks: 5,
          optionA: ExamBlockOption(content: 'Read the following sentences, spot the errors and rewrite the sentences correctly.\n(i) We bought some furnitures.\n(ii) I met an European at the University.\n(iii) Though he ran fast but he did not win.\n(iv) Cauvery flows through Trichy.\n(v) I sat besides my sister.'),
          optionB: ExamBlockOption(content: 'Fill in the blanks appropriately.\n(i) Your ring is __________. Do not __________ it. [loose/lose]\n(ii) Sheela went to the library, __________ [suitable question tag]\n(iii) __________ you go to a library, you will see different genres of books. [suitable link word]\n(iv) It __________ (rain) since last night. [correct tense form]'),
        ),
        ExamBlock(
          type: 'paragraph_text',
          content: "Preethi Srinivasan is a former cricketer from Tamilnadu. She played domestic cricket in the 1990s. At the age of eight, she was the youngest girl to play in the state Cricket Team. At the age of seventeen, She captained the Tamilnadu's women's under-19 cricket team in a National Tournament in 1997 and registered its only victory ever. In the following year, she suffered with a spinal cord injury in an accident that left her quadriplegic. Her own trauma inspired her to create soulfree, a foundation that aims to help Indian youth to cope with disabilities related to spinal cord injuries. In 2018, She received the Kalpana Chawla award for courage and daring enterprise.",
        ),
        ExamBlock(
          type: 'multi_subquestion',
          questionId: 'q47a',
          marks: 5,
          content: 'Read the following passage and answer the questions in your own words.',
          subQuestions: [
            ExamSubQuestion(id: 'q47a1', label: 'i', content: "What did Preethi Srinivasan play during the 1990's ?", marks: 1),
            ExamSubQuestion(id: 'q47a2', label: 'ii', content: 'Why was the soulfree Foundation created ?', marks: 1),
            ExamSubQuestion(id: 'q47a3', label: 'iii', content: 'When did she receive the Kalpana Chawla award ?', marks: 1),
            ExamSubQuestion(id: 'q47a4', label: 'iv', content: 'Did Preethi win a National Tournament ?', marks: 1),
            ExamSubQuestion(id: 'q47a5', label: 'v', content: 'Pick one word from the passage which is the opposite of "International".', marks: 1),
          ],
        ),
        ExamBlock(
          type: 'or_question',
          questionId: 'q47',
          marks: 5,
          optionA: ExamBlockOption(content: 'Read the following passage and answer the questions in your own words. (Questions i–v as listed above)'),
          optionB: ExamBlockOption(content: 'Write a conversation between two friends on reading an interesting novel.\n(Minimum of five exchange)'),
        ),
        ExamBlock(type: 'footer_note', content: '- o O o -'),
      ],
    ),
  ],
);
