import '../../models/exam_paper_model.dart';

const class12English2025Annual = ExamPaperData(
  paperId: 'class12-english-2025-annual',
  title: '2025 Annual Exam Paper',
  classLabel: 'Class 12',
  subject: 'English',
  duration: '3.00 Hours',
  maximumMarks: 90,
  totalPages: 8,
  pages: [
    ExamPage(
      pageNumber: 1,
      blocks: [
        ExamBlock(type: 'paper_header', content: 'Language — Part II — English'),
        ExamBlock(
          type: 'metadata_row',
          items: [
            MetadataItem(label: 'Time', value: '3.00 Hours'),
            MetadataItem(label: 'Maximum Marks', value: '90'),
            MetadataItem(label: 'Total Pages', value: '8'),
          ],
        ),
        ExamBlock(
          type: 'instructions',
          content: 'Instructions: (1) Check the question paper for fairness in printing. If there is any lack of fairness, inform the Hall Supervisor immediately. (2) Use Blue or Black ink pen to write and underline and pencil to draw diagrams.',
        ),
        ExamBlock(type: 'part_heading', content: 'PART - I'),
        ExamBlock(
          type: 'instructions',
          content: 'Note: (i) Answer all the questions. 20x1=20\n(ii) Choose the most appropriate answer from the given four alternatives and write both the option code and the corresponding answer for each question.',
        ),
        ExamBlock(
          type: 'instructions',
          content: 'Choose the most appropriate synonyms of the words underlined in the following sentences.',
        ),
        ExamBlock(
          type: 'mcq_question',
          questionId: 'q1',
          marks: 1,
          content: 'These two children had given me a profound lesson.',
          options: ['genuine', 'complete', 'prosaic', 'very great'],
        ),
        ExamBlock(
          type: 'mcq_question',
          questionId: 'q2',
          marks: 1,
          content: 'They only drink it in order to be warmed and stimulated.',
          options: ['perplexed', 'motivated', 'admired', 'discouraged'],
        ),
        ExamBlock(
          type: 'mcq_question',
          questionId: 'q3',
          marks: 1,
          content: 'Our father rejected it, saying it wouldn\'t be sturdy.',
          options: ['strong', 'fine', 'suitable', 'comfortable'],
        ),
        ExamBlock(
          type: 'instructions',
          content: 'Choose the most appropriate antonyms of the words underlined in the following sentences.',
        ),
        ExamBlock(
          type: 'mcq_question',
          questionId: 'q4',
          marks: 1,
          content: 'We came upon them in the windy and deserted square.',
          options: ['empty', 'uninhabited', 'isolated', 'occupied'],
        ),
        ExamBlock(
          type: 'mcq_question',
          questionId: 'q5',
          marks: 1,
          content: 'Fortuitously, a guest visited our house.',
          options: ['unfortunately', 'luckily', 'happily', 'peacefully'],
        ),
        ExamBlock(type: 'footer_note', content: '[ Turn over'),
      ],
    ),
    ExamPage(
      pageNumber: 2,
      blocks: [
        ExamBlock(
          type: 'mcq_question',
          questionId: 'q6',
          marks: 1,
          content: 'I experienced not only agony and fear but also anger.',
          options: ['surprise', 'pleasure', 'suffering', 'sorrow'],
        ),
        ExamBlock(
          type: 'mcq_question',
          questionId: 'q7',
          marks: 1,
          content: 'Choose the word that has been spelt correctly.',
          options: ['wearhouse', 'seperate', 'foreign', 'secretery'],
        ),
        ExamBlock(
          type: 'mcq_question',
          questionId: 'q8',
          marks: 1,
          content: 'Choose the word that is not a noun.',
          options: ['stimulate', 'destruction', 'strength', 'wisdom'],
        ),
        ExamBlock(
          type: 'mcq_question',
          questionId: 'q9',
          marks: 1,
          content: 'Fill in the blank with the appropriate word. There was a grand ________ of scattered plates and silverware after the show.',
          options: ['feeling', 'final', 'finally', 'finale'],
        ),
        ExamBlock(
          type: 'mcq_question',
          questionId: 'q10',
          marks: 1,
          content: 'Fill in the blank with the suitable phrasal verb. After a long break, the regiment began to ________ towards their destination.',
          options: ['set off', 'set up', 'set for', 'set in'],
        ),
        ExamBlock(
          type: 'mcq_question',
          questionId: 'q11',
          marks: 1,
          content: 'Choose the polite alternative for the underlined word in the following sentence. The burglars were sent to jail.',
          options: ['rehabilitation centre', 'asylum', 'prison', 'correctional facility'],
        ),
        ExamBlock(
          type: 'mcq_question',
          questionId: 'q12',
          marks: 1,
          content: 'Choose the suitable American English word equivalent to the British English word in the following sentence. Aswin bought sweets from the stall.',
          options: ['jelly', 'candies', 'muffins', 'cream'],
        ),
        ExamBlock(
          type: 'mcq_question',
          questionId: 'q13',
          marks: 1,
          content: 'Choose the correct combination of the compound word - \'software\'.',
          options: ['Noun + Adjective', 'Noun + Noun', 'Adverb + Adjective', 'Adjective + Noun'],
        ),
        ExamBlock(
          type: 'mcq_question',
          questionId: 'q14',
          marks: 1,
          content: 'Choose the word that can be blended with the word - \'smoke\'.',
          options: ['hail', 'mist', 'fog', 'snow'],
        ),
        ExamBlock(
          type: 'mcq_question',
          questionId: 'q15',
          marks: 1,
          content: 'Choose the correct meaning of the Idiom in the given sentence. When they had to climb through deep snow the party sometimes had to wait for the dust to settle.',
          options: ['to wait for a long time', 'to wait for a situation to become clear', 'to wait for the guide', 'to wait for the Sun to set'],
        ),
      ],
    ),
    ExamPage(
      pageNumber: 3,
      blocks: [
        ExamBlock(
          type: 'mcq_question',
          questionId: 'q16',
          marks: 1,
          content: 'Choose the suitable preposition to fill the blank in the following sentence. She was popular ________ her schoolmates.',
          options: ['along', 'with', 'among', 'between'],
        ),
        ExamBlock(
          type: 'mcq_question',
          questionId: 'q17',
          marks: 1,
          content: 'Choose the right expansion for TNPSC.',
          options: ['Tamilnadu Public Science Council', 'Tamilnadu People Service Commission', 'Tamilnadu Public Service Commission', 'Tamilnadu Pupil Service Commission'],
        ),
        ExamBlock(
          type: 'mcq_question',
          questionId: 'q18',
          marks: 1,
          content: 'Choose the appropriate linker. We fail to harness the rain water, ________ we suffer.',
          options: ['consequently', 'nevertheless', 'besides', 'whereas'],
        ),
        ExamBlock(
          type: 'mcq_question',
          questionId: 'q19',
          marks: 1,
          content: 'Choose the appropriate determiner. There are only ________ chocolates left for you.',
          options: ['a few', 'more', 'much', 'a little'],
        ),
        ExamBlock(
          type: 'mcq_question',
          questionId: 'q20',
          marks: 1,
          content: 'Choose the right article and fill in the blank. Radha is ________ tallest of the three.',
          options: ['the', 'an', 'no Article', 'a'],
        ),
        ExamBlock(type: 'part_heading', content: 'PART - II'),
        ExamBlock(type: 'section_heading', content: 'SECTION - 1'),
        ExamBlock(
          type: 'instructions',
          content: 'Choose any four of the following sets of poetic lines and answer the questions that follow. 4x2=8',
        ),
        ExamBlock(
          type: 'multi_subquestion',
          questionId: 'q21',
          marks: 2,
          content: 'This is my son, mine own Telemachus\nTo whom I leave the sceptre and the isle\nWell-loved of me,',
          subQuestions: [
            ExamSubQuestion(id: 'q21a', label: 'a', content: 'What does \'the sceptre\' mean ?', marks: 1),
            ExamSubQuestion(id: 'q21b', label: 'b', content: 'Whom does Ulysses entrust his Kingdom to ?', marks: 1),
          ],
        ),
        ExamBlock(
          type: 'multi_subquestion',
          questionId: 'q22',
          marks: 2,
          content: 'A creeper climbs, in whose embraces bound\nNo other tree could live.',
          subQuestions: [
            ExamSubQuestion(id: 'q22a', label: 'a', content: 'How does the tree survive the tight hold of the creeper ?', marks: 1),
            ExamSubQuestion(id: 'q22b', label: 'b', content: 'Pick out the words in alliteration.', marks: 1),
          ],
        ),
        ExamBlock(type: 'footer_note', content: '[ Turn over'),
      ],
    ),
    ExamPage(
      pageNumber: 4,
      blocks: [
        ExamBlock(
          type: 'multi_subquestion',
          questionId: 'q23',
          marks: 2,
          content: 'Seeking the bubble reputation\nEven in the cannon\'s mouth.',
          subQuestions: [
            ExamSubQuestion(id: 'q23a', label: 'a', content: 'Mention the figure of speech employed here.', marks: 1),
            ExamSubQuestion(id: 'q23b', label: 'b', content: 'What does \'cannon\' mean ?', marks: 1),
          ],
        ),
        ExamBlock(
          type: 'multi_subquestion',
          questionId: 'q24',
          marks: 2,
          content: 'Our gates were strong, our walls were thick,\nSo smooth and high, no man could win.',
          subQuestions: [
            ExamSubQuestion(id: 'q24a', label: 'a', content: 'How safe was the castle ?', marks: 1),
            ExamSubQuestion(id: 'q24b', label: 'b', content: 'What was the firm belief of the soldiers ?', marks: 1),
          ],
        ),
        ExamBlock(
          type: 'multi_subquestion',
          questionId: 'q25',
          marks: 2,
          content: 'Tell him solitude is creative if he is strong\nand the final decisions are made in silent rooms.',
          subQuestions: [
            ExamSubQuestion(id: 'q25a', label: 'a', content: 'Can being in solitude help a strong human being ? How ?', marks: 1),
            ExamSubQuestion(id: 'q25b', label: 'b', content: 'Identify the poetic device used here.', marks: 1),
          ],
        ),
        ExamBlock(
          type: 'multi_subquestion',
          questionId: 'q26',
          marks: 2,
          content: 'With neck out-thrust, you fancy how,\nLegs wide, arms locked behind,\nAs if to balance the prone brow\nOppressive with its mind.',
          subQuestions: [
            ExamSubQuestion(id: 'q26a', label: 'a', content: 'Identify the rhyme scheme of the given lines.', marks: 1),
            ExamSubQuestion(id: 'q26b', label: 'b', content: 'Whose action is described here ?', marks: 1),
          ],
        ),
        ExamBlock(type: 'section_heading', content: 'SECTION - 2'),
        ExamBlock(type: 'instructions', content: 'Do as directed. Answer any three questions. 3x2=6'),
        ExamBlock(
          type: 'question',
          questionId: 'q27',
          marks: 2,
          content: 'Please tell me what the time is.\n(Rewrite as a Simple sentence)',
        ),
        ExamBlock(
          type: 'question',
          questionId: 'q28',
          marks: 2,
          content: 'The chief guest was distributing the prizes.\n(Change into Passive Voice)',
        ),
        ExamBlock(
          type: 'question',
          questionId: 'q29',
          marks: 2,
          content: 'Unless we plant more trees, we cannot save our planet.\n(Rewrite using \'if\' without changing the meaning)',
        ),
        ExamBlock(
          type: 'question',
          questionId: 'q30',
          marks: 2,
          content: 'Change into reported speech.\nThe manager said, "I will speak to you on Friday."',
        ),
      ],
    ),
    ExamPage(
      pageNumber: 5,
      blocks: [
        ExamBlock(type: 'part_heading', content: 'PART - III'),
        ExamBlock(type: 'section_heading', content: 'SECTION - 1'),
        ExamBlock(type: 'instructions', content: 'Explain any two of the following with reference to the context. 2x3=6'),
        ExamBlock(
          type: 'question',
          questionId: 'q31',
          marks: 3,
          content: 'Brutes have been gentled where lashes failed.',
        ),
        ExamBlock(
          type: 'question',
          questionId: 'q32',
          marks: 3,
          content: 'It is the tree\'s lament, an eerie speech, ...',
        ),
        ExamBlock(
          type: 'question',
          questionId: 'q33',
          marks: 3,
          content: 'To follow knowledge like a sinking star,\nBeyond the utmost bound of human thought.',
        ),
        ExamBlock(type: 'section_heading', content: 'SECTION - 2'),
        ExamBlock(type: 'instructions', content: 'Answer any two of the following questions in not more than 30 words each. 2x3=6'),
        ExamBlock(
          type: 'question',
          questionId: 'q34',
          marks: 3,
          content: 'Describe the appearance of Nicola and Jacopo.',
        ),
        ExamBlock(
          type: 'question',
          questionId: 'q35',
          marks: 3,
          content: 'What did Tenzing and Edmund Hillary gift to the Gods of lofty Summit ?',
        ),
        ExamBlock(
          type: 'question',
          questionId: 'q36',
          marks: 3,
          content: 'Why did the family find it difficult to make a chair ?',
        ),
        ExamBlock(type: 'section_heading', content: 'SECTION - 3'),
        ExamBlock(type: 'instructions', content: 'Answer any three of the following. 3x3=9'),
        ExamBlock(
          type: 'question',
          questionId: 'q37',
          marks: 3,
          content: 'Create a catchy slogan for each of the following topics.\n(a) Junk Food\n(b) Save Water\n(c) Eye Donation',
        ),
        ExamBlock(
          type: 'question',
          questionId: 'q38',
          marks: 3,
          content: 'Extend the conversation with three more relevant exchanges.\nPassenger : Has the Rockfort Express arrived ?\nRailway Staff : No, it will arrive in ten minutes.\nPassenger : ________________\nRailway Staff : ________________\nPassenger : ________________\nRailway Staff : ________________\nPassenger : ________________\nRailway Staff : ________________',
        ),
        ExamBlock(type: 'footer_note', content: '[ Turn over'),
      ],
    ),
    ExamPage(
      pageNumber: 6,
      blocks: [
        ExamBlock(
          type: 'question',
          questionId: 'q39',
          marks: 3,
          content: 'Study the following pie-chart and answer the questions given below.\nThe pie-chart represents the number of participants in School Annual Day events.\n(Folk Songs: 20, Dance: 35, Miming: 15, Drama: 20, Classical Songs: 10)\n(i) How many students participated in dance and drama ?\n(ii) Which event has the least number of participants ?\n(iii) Write true or false : Drama and Folk Songs have equal number of participants.',
        ),
        ExamBlock(
          type: 'chart_image',
          src: '',
          altText: 'Pie chart showing number of participants in School Annual Day events: Folk Songs (20), Dance (35), Miming (15), Drama (20), Classical Songs (10).',
          caption: '',
          renderHint: 'image',
        ),
        ExamBlock(
          type: 'question',
          questionId: 'q40',
          marks: 3,
          content: 'Describe the process of preparing apple juice.',
        ),
        ExamBlock(type: 'part_heading', content: 'PART - IV'),
        ExamBlock(type: 'instructions', content: 'Answer the following. 7x5=35'),
        ExamBlock(
          type: 'or_question',
          questionId: 'q41',
          marks: 5,
          optionA: ExamBlockOption(content: 'Answer the following in a paragraph of about 150 words.\nSummarise George Orwell\'s distinctive ideas in "A Nice Cup of Tea".'),
          optionB: ExamBlockOption(content: 'Answer the following in a paragraph of about 150 words.\nWhat do you infer from Gardiner\'s essay \'On the Rule of the Road\' ?'),
        ),
        ExamBlock(
          type: 'or_question',
          questionId: 'q42',
          marks: 5,
          optionA: ExamBlockOption(content: 'Answer the following in a paragraph of about 150 words.\nDescribe the various stages of a man\'s life picturised in the poem "All the World\'s a Stage."'),
          optionB: ExamBlockOption(content: 'Answer the following in a paragraph of about 150 words.\nWhat is the role of the young soldier in the victory of the French at Ratisbon ?'),
        ),
      ],
    ),
    ExamPage(
      pageNumber: 7,
      blocks: [
        ExamBlock(
          type: 'or_question',
          questionId: 'q43',
          marks: 5,
          optionA: ExamBlockOption(content: 'Develop the following hints into a paragraph of about 150 words.\nPi Patel - Indian boy - 227 days - shipwreck - Bengal tiger - Richard Parker - hyena - search water - succeeded - cans of drinking water - left Richard Parker in a jungle - reunited.'),
          optionB: ExamBlockOption(content: 'Develop the following hints into a paragraph of about 150 words.\nThe Scientist - Venus - children wait for Sun - seven years - getting ready - Margot - William - rain stopped - Sun comes out - started raining - let her out.'),
        ),
        ExamBlock(
          type: 'or_question',
          questionId: 'q44',
          marks: 5,
          optionA: ExamBlockOption(
            content: 'Write a summary of the following passage.\n\nIn recent years, environmental pollution has increased so much that it has become a global problem. Almost all cities in Asian Countries face this problem. The causes of environmental pollution are quite obvious. Vehicles burn petrol and emit toxic smoke. Various chemical factories pollute the air as well as water. Water is so contaminated because of effluents that both marine and organic life is destroyed. The ozone layer has developed a big hole due to this pollution and lets in harmful rays.\n\nThis environmental pollution has begun to affect human health. School children are easy victims to this pollution because they come in direct contact with fumes from the exhaust pipes of the vehicles. Crops have failed in many places. Flora and Fauna have been deeply affected. The sea water level has begun to rise and coastal cities may sink due to this.\n\nWe need to pay attention to this as human survival is in grave danger. More and more trees should be planted in every available inch of land. A public awareness programme must be launched to fight this manmade menace.',
          ),
          optionB: ExamBlockOption(content: 'Write a paragraph in about 150 words on \'The Hazards of the Internet\'.'),
        ),
        ExamBlock(
          type: 'or_question',
          questionId: 'q45',
          marks: 5,
          optionA: ExamBlockOption(content: 'Write a letter to the Manager of Waves Furniture Company ordering furniture for a coaching centre. Include the following details: description of the furniture, number of pieces, mode of payment, time and delivery options.'),
          optionB: ExamBlockOption(content: 'Write a letter to your friend describing how you celebrated Pongal.'),
        ),
        ExamBlock(type: 'footer_note', content: '[ Turn over'),
      ],
    ),
    ExamPage(
      pageNumber: 8,
      blocks: [
        ExamBlock(
          type: 'or_question',
          questionId: 'q46',
          marks: 5,
          optionA: ExamBlockOption(
            content: 'Fill in the blanks appropriately.\n(i) Nobody can solve this issue, ________ ? [Add a suitable question tag]\n(ii) She bought ________ useful gadget. [Fill in with appropriate determiner]\n(iii) I ________ like to have a cup of tea. [Fill in with suitable modal verb]\n(iv) The police tried to ________ the information from the culprit regarding the source of ________ materials. [elicit/illicit]',
          ),
          optionB: ExamBlockOption(
            content: 'Identify the error in each of the following sentences and correct them appropriately.\n(i) Oxygen is more heavier than hydrogen.\n(ii) It was a shame breaking up.\n(iii) Professor Uma is not only a writer but an actor.\n(iv) A man walked through the bank of the river.\n(v) If you exercise regularly, you would become strong.',
          ),
        ),
        ExamBlock(
          type: 'or_question',
          questionId: 'q47',
          marks: 5,
          optionA: ExamBlockOption(content: 'Prepare a dialogue between Rahim and Ragav discussing their preparation for a tour, in not less than five exchanges.'),
          optionB: ExamBlockOption(
            content: 'Read the following passage and answer the questions given below.\n\nWhen Andrew Carnegie came to America from Scotland, he was just a lad. He started out by running errands and ended up as one of the largest steel manufacturers in the United States. Someone once asked Mr. Carnegie how he dealt with people. Andrew Carnegie replied, "Dealing with people is a lot like digging for gold. When you go digging for an ounce of gold, you have to move tons of dirt. But when you go digging, you don\'t go looking for the dirt, you go looking for the gold."\n\nAndrew Carnegie\'s reply has a very important message. Though sometimes it may not be apparent, there is something positive in every person and every situation. We have to look deep for the positive.\n\nQuestions:\n(i) Who is Andrew Carnegie ?\n(ii) Where did he come from ?\n(iii) How did Carnegie start out in his career ?\n(iv) What does Carnegie compare dealing with people to ?\n(v) Pick one word from the passage that means the opposite of \'shallow\'.',
          ),
        ),
        ExamBlock(type: 'footer_note', content: '- o 0 o -'),
      ],
    ),
  ],
);
